def part_1():
	cycle = register = 1
	signal_strengths = []
	for task in instructions:
		if cycle%40 == 20:
			signal_strengths.append(cycle*register)
		if task[0] == "noop":
			cycle += 1
		elif task[0] == "addx":
			if (cycle+1)%40 == 20:
				signal_strengths.append((cycle+1)*register)
			cycle += 2
			register += int(task[1])
	return sum(signal_strengths)

def part_2():
	cycle = sprite_mid = 1
	image = [['.' for _ in range(40)] for _ in range(6)]
	for task in instructions:
		row,col = divmod(cycle-1,40)
		if col in range(sprite_mid-1,sprite_mid+2):
			image[row][col] = '#'
		cycle += 1
		if task[0] == "addx":
			row,col = divmod(cycle-1,40)
			if col in range(sprite_mid-1,sprite_mid+2):
				image[row][col] = '#'
			cycle += 1
			sprite_mid += int(task[1])
	return image

with open("Program Instructions.txt",'r') as my_file:
	instructions = [task.strip('\n').split(' ') for task in my_file.readlines()]

print(f"Sum of six signal strengths is {part_1()}.")
print("\nImage generated by program : \n")
for row in part_2():
	print(''.join(row))